version: '3'
services:
  mysql:
   container_name: nanocorpmysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: myuser
    MYSQL_PASSWORD: mypassword
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql

